### ISSUE TITLE
Fatal Error on Startup After Home Assistant Core 2023.2.1 Upgrade

### ISSUE THREAD

**Issue by nsheldon** [hass-emulated-hue/core#394] opened 2023-02-03 22:38 UTC
### Description

Emulated HUE fails to start after upgrading to Home Assistant Core 2023.2.1. Fatal error in logs.

### Expected behavior

Emulated HUE should start without errors.

### Reproduction steps

Install and configure the Emulated HUE 0.3.0 add-on in Home Assistant Core 2023.1.7 on Home Assistant OS 9.5 (on Home Assistant Blue hardware). Ensure Emulated HUE starts. Then upgrade Home Assistant Core to 2023.2.1.

### Relevant log output

```shell
s6-overlay-suexec: fatal: can only run as pid 1
```

### Operating system

HassOS

### Install method

HassOS Addon

### Version

0.3.0

### Any other information that may be helpful

In attempting to troubleshoot the issue, I uninstalled the Emulated HUE add-on and re-installed it. This seems to have resolved the issue. I’m just reporting it in case others see this issue as well.

**Comment by alexyao2015** [comment] 2023-02-03 22:42
Thanks for reporting. This was a duplicate of #391 which was later fixed. Uninstalling and reinstalling should fix this issue as it will cause home assistant to clear it's cache.

**Closed by alexyao2015** 2023-02-03 22:42 UTC
Labels: bug

**Comment by nsheldon** [comment] 2023-02-03 22:56
Thanks! Sorry for the duplicate. I guess I didn’t use the correct search terms when searching for known issues.
