### ISSUE TITLE
Please allow Hue Essentials Effects to be saved on the emulated bridge

### ISSUE THREAD

**Issue by martindinicolino** [hass-emulated-hue/core#401] opened 2023-02-09 07:13 UTC
### Description

Currently Effects created/purchased in Hue Essentials can not be saved to the emulated hue bridge. Attempting to do so returns an error message every time (ERROR Unexpected response from bridge. Please try again later. 404 - /sensors - unknown request).

### Use Case

Effects need to be saved on the emulated bridge in order to be executed from Siri Shortcuts, or the Hue Essentials API (thus allowing them to be executed automatically and/or remotely).

### Any other information that may be helpful

It is currently only possible to save the effect on a mobile device, this however means that the effect can not be triggered automatically/remotely.

**Comment by alexyao2015** [comment] 2023-02-09 15:53
Duplicate of #50

**Closed by alexyao2015** 2023-02-09 15:53 UTC
Labels: enhancement

**Comment by martindinicolino** [comment] 2023-02-09 16:17
> Duplicate of #50

Thank you, I read through the issue you linked, but it‘s still not possible to store effects on the bridge. Is there any way of getting this to work?
