### ISSUE TITLE
expose sensor api

### ISSUE THREAD

**Issue by ktown007** [hass-emulated-hue/core#139] opened 2021-03-14 14:43 UTC
**Is your feature request related to a problem? Please describe.**

I would like HA sensor to be usable in Alexa. Currently they can come in as lights however cannot be used as a trigger for a routine. All sensors as lights was too many.

**Describe the feature that you would like to be added**

configure a list of sensor entities to expose via http://<HUE_BRIDGE>/api/<USER_ID>/sensors

**Describe alternatives you've considered**

[role my own](https://wolfgang-ziegler.com/blog/hue-motion-sensor-api)

**Describe your use case for this feature**

allow Alexa routines to be triggered from HA sensors or automations via helpers

**Additional context**

For routines my physical hue hub shows motion sensors in Alexa but not temperature or lux. Some experimentation around what type of senses which work will be needed.

**Comment by alexyao2015** [comment] 2021-03-14 14:47
I don't have a hue hub to figure this out myself and it seems frivolous given that home assistant already has alexa integration.

**Comment by alexyao2015** [comment] 2021-03-14 14:53
This request actually is a duplicate of #50, but again its difficult due to lack of the actual hub or responses.

**Closed by alexyao2015** 2021-03-14 14:53 UTC
Labels: enhancement

**Comment by ktown007** [comment] 2021-03-14 16:33
this link gives some of the details of the json: https://wolfgang-ziegler.com/blog/hue-motion-sensor-api
I can pull the sensor examples from my hub as another reference. I can also assist with testing. I am new to HASS but experienced with API's
